### ISSUE TITLE
Can we use a specific file for storing optimizeDeps instead of a field of package.json? 

### ISSUE THREAD

**Issue by zheeeng** [antfu/vite-plugin-optimize-persist#2]
It's about Vite but related to vite-plugin-optimize-persist.
For a huge project, manipulate the package.json pollutes it and is not elegant enough. Separate optimizeDeps to a specific file for storing it is a conventional way.

**Comment by antfu** [comment]
Yes, https://github.com/antfu/vite-plugin-package-config/blob/cdb5f47e5817e15420d704d2e08db5b052116878/src/index.ts#L10-L13
