### ISSUE TITLE
Add indirect imported modules as optimizeDeps in PNPM monorepo cause force resoving failed 

### ISSUE THREAD

**Issue by zheeeng** [antfu/vite-plugin-optimize-persist#3]
In pnpm monorepo project, modules are isolated by package scopes.

Assume this structure:
1. Vite entry project sub-package A imports sub-package B.
```ts
// @monorepo/packageA
import { B } from '@monorepo/packageB'
```

2. sub-package B  import cjs packages C, D, E, they are installed as dependencies of sub-package B.
```ts
// @monorepo/packageB
import C from 'c';
import D from 'd';
import E from 'd';
```

3. plugin writes the B's dependencies C, D, E as optimizeDeps of sub-package A. Cause dev error after cleaning node_modules:
![image](https://user-images.githubusercontent.com/1303154/137500094-9a70f301-2806-436c-a215-d4a0fdae8526.png)

**Comment by antfu** [comment]
You could have them in the `exclude` list and this plugin will ignore them.

**Comment by zheeeng** [comment]
> You could have them in the `exclude` list and this plugin will ignore them.

Is there a way not to exclude these dynamic-generated dependencies manually?

**Comment by zheeeng** [comment]
Made a PR for this issue: https://github.com/antfu/vite-plugin-optimize-persist/pull/4

by passing a predictor for checking whether a module is listed as dependencies in package.json
